### Find all content
GET http://localhost:8080/api/content
### Find content by id
GET http://localhost:8080/api/content/1
### Post content
POST GET http://localhost:8080/api/content 
Content-Type: application/json

{ 
            "id" : 2,
            "title" : "Glucose Toujours",
            "description" : "Glucose Toujours, le media qui en dit long sur le diabète !",
            "url" : "https://glucosetoujours.com/",
            "content" : "Glucose Toujours, le media qui en dit long sur le diabète !",
            "mainPicture" : "https://glucosetoujours.com/_next/image?url=%2Fpictures%2Flogo_anime_once_white.gif&w=1920&q=75",
            "creationDate" : null,
            "lastUpdateDate" : null,
            "status" : "IDEA",
            "contentType" : "PERSONALIZED"
}
